oh-my-fish/oh-my-fish

pkg/omf/cli/omf.install.fish
When installing packages (plugins) or themes using a URL, we should
strip the plugin-/pkg-/theme- from the repository name if it exists.
=> Remove pkg-/theme- from folder name

db/pkg/apt
This adds [my apt plugin](https://github.com/coderstephen/plugin-apt) to the general package database. This is a package that I've developed and tweaked over the years that started out as a bash script. When I switched to Fish a few years ago, this script was rewritten in Fish and became a function, which became an OMF plugin when I started using the framework several months ago.
I originally kept the package inside my personal dotfiles repo, but I figured that other Debian or Ubuntu users might benefit from the package as well.
Thoughts on the package?
=> Add apt plugin to db

pkg/omf/cli/omf.bundle.add.fish, pkg/omf/cli/omf.bundle.install.fish, pkg/omf/cli/omf.bundle.remove.fish, pkg/omf/cli/omf.install.fish, pkg/omf/cli/omf.remove_package.fish, pkg/omf/omf.fish
Improving the work done in #15, this PR moves bundle related functions to `omf.bundle` namespace, splitting them in its own files. I think this is necessary to make the code cleaner and more maintainable.
This PR also fixes #22 and include work done on PR #21 as a batch. Thanks @scorphus :)
=> bundle: move related functions to omf.bundle namespace

pkg/omf/completions/omf.fish
This PR replaces our own completion functions by fish builtin ones:
* `__omf.is_single_opt` → `__fish_use_subcommand`
* `__omf.opt_is` → `__fish_seen_subcommand_from`
While using this completions I couldn't reproduce a case where the completion computation freeze the shell, e.g. while typing `omf install`.
=> Use standard fish functions for completion

README.md
This PR adds manual update instructions to main README. It's very important, as various issues emerged in last days (see #33, #7, oh-my-fish/plugin-rbenv#6) and we need a central place to put this instructions, instead of copy-pasting them into issues.
=> Include update instructions

README.md, docs/Themes.md, tools/generate-themes-doc.fish
Wanted to browse thru all the available themes, but could not find a centralized place for this. This PR contains a `bin/generate-themes-doc.fish` which generates `docs/Themes.md` that can be used for previewing the themes.
See https://github.com/Pyppe/oh-my-fish/blob/master/docs/Themes.md
=> Add generate-themes-doc.fish

pkg/omf/cli/omf.destroy.fish, pkg/omf/cli/omf.remove_package.fish, pkg/omf/omf.fish
**omf.destroy** was broken because of a [premature refresh].
And with [this code] it was giving the impression that omf was hanging while in fact fish was running without a display.
When fixing the bug I assumed that remove_package do the minimal (handle only one pkg)
At the time of the PR the indent in [omf.remove_package.fish] might be broken.
I am now working on [omf.destroy.fish] to find the most recent backup of config.fish (for this PR)
[premature refresh]: https://github.com/oh-my-fish/oh-my-fish/blob/4b0dbc270b9ab73d56aa0d07d820243d22479892/pkg/omf/cli/omf.remove_package.fish#L40
[this code]: https://github.com/oh-my-fish/oh-my-fish/blob/4b0dbc270b9ab73d56aa0d07d820243d22479892/pkg/omf/cli/omf.destroy.fish#L4
[omf.remove_package.fish]: …
=> Fixes on omf destroy and omf.remove_package

AUTHORS, LICENSE
Ping @bucaran @bobthecow @derekstavis @scorphus 
This is the message sent to GitHub with for the reconciliation:
> I have talked to @bpinto and his other collaborators and decided that is
> the best for everyone to reconcile and conclude our litigation amicably
> with the following conditions:
>
> * The license read Copyright (c) 2015 Oh My Fish!
> * AUTHORS file.
> * Bruno and Justin remain as admins.
> * Scorphus, derekstavis and bucaran become collaborators.
> * We swear not to fight over copyright issues again.
>
> You may have the DMCA revoked at your earliest convenience.
=> DMCA Agreement

README.md
Spacer still works just as good.
This will make Chrome and its siblings not display a broken image placeholder
in the spacer.
Confirmed OK on Firefox and Safari.
=> Remove src attribute from spacer image in the README

README.md
Addresses #40 by briefly documenting init.fish file.
=> README: add custom config file documentation

db/pkg/tmux-zen
Adds my highly opinionated tmux plugin, [tmux-zen](https://github.com/coderstephen/tmux-zen), to the package database.
=> Add tmux-zen plugin to db

db/pkg/kill-on-port
Is there a good way of specifying transient dependencies? This pkg requires the getopts pkg for example...?
=> Add kill-on-port pkg

.travis.yml, docs/Themes.md, tests/test-generate-themes-doc.fish, tools/generate-themes-doc.fish
* Run with Travis CI
* Fail build if `docs/Themes.md` is no longer up-to-date
Here's Travis examples:
* [Build fails](https://travis-ci.org/Pyppe/oh-my-fish/builds/82439638)
* [Build succeeds](https://travis-ci.org/Pyppe/oh-my-fish/builds/82439947)
The iffy thing here is that whenever any theme README gets updated, the Travis-build will fail... Any thoughts?
=> Add test-generate-themes-doc.fish

bin/install, init.fish, templates/config.fish
This PR sets the default value of `OMF_CONFIG` variable in framework `init.fish` file. The variable can still be overridden by the user by setting it on `~/.config/fish/config.fish file`.
This is in preparation to rewriting install script in plain fish, which will ditch config template and stop replacing `config.fish`contents in favor of just appending Oh My Fish startup.
=> Move $OMF_CONFIG variable to $OMF_PATH/init.fish

README.md, docs/en-US/FAQ.md, docs/zh-CN/FAQ.md, docs/zh-CN/README.md, init.fish, templates/config.fish
To allow variables to be set before plugins (or Oh My Fish) are loaded, you can place scripts in `$OMF_CONFIG/before.init.fish`. For consistency, `$OMF_CONFIG/init.fish` is now `$OMF_CONFIG/after.init.fish`.
This doesn't currently make considerations for backwards compatibility.
=> Split custom "init.fish" into clearer "before.init.fish" and "init.fish"

pkg/omf/cli/omf.repo.pull.fish
Stash is a shell script that does not support `--git-dir`, not even on
latest versions. We need to use `git -C` which was only added on recent
versions of `git`.
`omf update` will fail in case omf need needs to run `git stash` and
git is not compatible.
=> Stash does not support --git-dir

README.md, bin/install, docs/zh-CN/README.md
This fixes some issues we had with the use of `source` in install script by going back to invoking `fish` on install script.
=> install: Replace source by fish invocation

pkg/omf/cli/omf.destroy.fish
When calling `omf destroy`, the `bundle` file is completely erased
because we are calling `remove_package` on each installed package. We
don't want to erase that file, we just want to emit the event and later
on remove the code, which is done with `rm -rf "$OMF_PATH"`.
=> Only emit uninstall_* event on `omf destroy`

lib/refresh.fish
Fixes an issue with history between shell reloads via refresh function call.
As `exec` replaces the current process in a non-gently fashion, the
persistent history could be out of sync with the in-memory history.
Calling `history --save` before `exec` should force the shell to persist the
history before replacing the current process.
=> Save history before replacing shell process

lib/README.md, lib/autoload.fish
Address the use case of autoload path removal, which allows themes
and packages definitions to be unloaded from running fish session.
This paves the way for allowing us to reload Oh My Fish without 
`exec`ing the shell, and thus overcoming the known issues with it.
=> Implement `autoload -e` option to remove from autoload paths

pkg/omf/cli/omf.bundle.add.fish
`omf theme` was persisting the installed theme twice, one time on `omf.install` and other time on `omf.bundle.add`.
=> bundle.add: fix theme being persisted twice

pkg/omf/cli/omf.check.fish_prompt.fish, pkg/omf/cli/omf.doctor.fish, pkg/omf/cli/omf.install.fish, pkg/omf/cli/omf.theme.fish, pkg/omf/cli/omf.xdg.config_home.fish, pkg/omf/omf.fish
**Depends upon #99**
The activation of a theme is now done in two phases of four steps:
+ Theme validation
- If not installed, install target theme
- Locate the current and target theme in `$OMF_CONFIG` or `$OMF_PATH`
- Check existence or create fish user function path
- Check for conflicting `fish_prompt`, abort if found
+ Theme activation
- Remove current theme from autoloading paths
- Add target theme to autoloading path
- Persist selected theme to `$OMF_CONFIG/theme`
- Link target theme's `fish_prompt` to user's
This approach brings two major advantages:
- Theme prompt now shows accordingly in `fish_config` web interface
- Faster theme changes, reducing it from seconds to some milis
- Avoids calling refresh, which makes users much more happy
Results:
* A faster theme changing …
=> Rework omf theme code: Integrate with fish_config, ditch refresh calls

pkg/omf/cli/omf.list_installed_packages.fish
As #115 migrated list functions, after updating Oh My Fish code
the omf.list_installed_packages gets removed, but is still being
used by the update code.
This commit fixes it by providing a wrapper function.
=> Fixes a regression in update process added in #115

pkg/omf/cli/omf.install.fish, pkg/omf/cli/omf.install_package.fish, pkg/omf/cli/omf.packages.list.fish, pkg/omf/cli/omf.theme.fish, pkg/omf/cli/omf.update.fish, pkg/omf/omf.fish
This series breaks install code monolith by splitting
the update code out of it and also by rewriting install
code.
Also fixes some known issues:
- #119 which tries to update local packages and even
omf package
- Installing plugins form URLs ended in `.git` now
works correctly
- When using `omf install <package>`, don't refresh 
the shell if nothing was installed
This series also changes the behavior of `omf theme`,
which now don't install or update themes when used,
rather displaying a message guiding the user to use
`omf install`.
=> Overhaul install and update code

lib/require.fish
`require` sources plugin's `init.fish` files, which are supposed to
declare an `init` function. Although we source the file, we aren't
cleaning up the declared function. This PR fixes this.
=> require: Cleanup previously sourced init functions

pkg/omf/cli/omf.bundle.install.fish, pkg/omf/omf.fish
Rewrites the code, as now `omf.install` is type
agnostic, and any -- preceded parameter will
be interpreted as package name.
In case of #123 it was breaking on a 
`basename` call just for the fun of
debugging :trollface:.
=> Rewrite bundle install to conform with latest `omf.install` interface

db/pkg/vcs
Add VCS plugin to registry. This plugin aims to be a dependency for themes which want to display version control related stuff. Currently the supported VCS are Git,  Mercurial and SVN.
The plugin is optimised for speed and performs very well when using Git, which is fast by nature. While using Mercurial we depend on `hg` speed, and thus, it's slower than Git. The same applies to SVN.
The API docs is still TBD, but it's not impeditive to the merge, IMHO. I also have a version of default theme which is already migrated to vcs plugin in work conditions, and the idea is to start migrating themes by it.
=> registry: add vcs plugin

pkg/omf/cli/omf.repo.pull.fish
This PR gives some Dont Repeat Yourself to `omf.repo.pull`.
It does it by defining functions which inherit the boring and repetitive git repository flags (`--git-dir "$repo_dir"/.git --work-tree "$repo_dir"`). This way the code almost fits in 80 columns :stuck_out_tongue: 
This is in very RFC state. Please review :+1:
=> omf.repo.pull: Use helper functions to fix code repetition

lib/autoload.fish
When using `autoload -e` we currently do a copy of destination function path's content,
modify it and then set it back. This was done as a workaround for using `set -e` with a
precedency issue in `set -e $dest[1]` usage, which is solved by using `set -e {$dest}[1]`.
=> autoload: Use `set -e` to remove components from paths

docs/Themes.md, tools/generate-themes-doc.fish
* Resolves oh-my-fish/oh-my-fish#116
=> Add namespaces to generate-themes-doc.fish

pkg/omf/cli/omf.destroy.fish, pkg/omf/cli/omf.packages.list.fish
This PR fixes the previously `basename`-function-masked usage of `basename` command.
All `basename`s which receives more than one parameter were converted to `basename -a`.
=> packages.list: Use basename -a with multiple paths

pkg/omf/cli/omf.packages.list.fish
I found two additional cases where basename was mistakenly used.
=> Fix more wrong basename usage cases

pkg/omf/omf.fish
Since `test` interprets arguments starting with a single dash as
options when comparing `test -h = --help` just swap parameter
orders as in `test --help = -h`. Also related to issue #161 is the
issue from fish repository at fish-shell/fish-shell#2332
=> Fix #161 by inverting test argument order 

pkg/omf/cli/omf.packages.list.fish
When using basename without any arguments, a usage helper as following
is displayed:
```
usage: basename string [suffix]
basename [-a] [-s suffix] string [...]
```
When listing the installed packages, if no theme was installed (e.g.
first installation), the `themes/` folder are empty and the usage helper
is displayed. This change addresses it by suppressing the message.
=> Suppress basename usage output

lib/require.fish, pkg/omf/cli/omf.bundle.install.fish, pkg/omf/cli/omf.install.fish, pkg/omf/cli/omf.update.fish
This PR adds automatic dependency loading to packages. Fixes #64 
Packages must include a `bundle` file in which dependencies are
declared in the same syntax as `$OMF_CONFIG/bundle` file.
On package installation we install the declared bundle.
On shell startup we load the dependencies from the bundle file.
=> Implement automatic dependency resolution

README.md
* The English README.md had a link to FAQ that does not work anymore given that it has been localized to `zh-CN` too. This commit makes sure that the link to FAQ in the English article points to the correct part of the correct file.
=> readme: Fix wrong link to FAQ

pkg/omf/templates/pkg/README.md, pkg/omf/templates/themes/README.md
Changes the scaffolded theme/plugin README, including a new, revamped look, more aligned with current Oh My Fish README. This PR happens to fix two additional items:
=> omf/templates: Align README headers based on omf's

db/pkg/homebrew-command-not-found
This plugin auto loads homebrew command not found.
=> Add homebrew command not found plugin

pkg/omf/omf.fish
`omf theme` now lists the current, installed and other available themes in different colors to mark their status.
Current theme is emphasized with `omf::em`,
installed themes are displayed normally,
and other available themes are dimmed with `omf::dim`.
Implementation is a bit hacky, but I didn't want to clutter `omf.fish` with very mini-functions specific only to the `theme` sub-command.
Has been tested on Fish 2.2.0, running on Fedora 23 (x64).
Mac OSX behavior should still be tested before merging to master (different `sed` syntax?)
**Edit:**
1. I fixed the editing errors of the last commit, please reconsider. Sorry for wasting your time with a faulty submission.
2. The regular expression that was supposed to highlight the current theme allowed partial matches, so that when applying …
=> Better organized 'omf theme' output

pkg/omf/cli/omf.bundle.install.fish, pkg/omf/cli/omf.bundle.remove.fish, pkg/omf/cli/omf.install.fish, pkg/omf/util/omf.package_name.fish
As requested in #152.
Does not solve #191. Prefer to infer package type from metadata in `package` file, as suggested in #196.
=> Support omf- prefix for packages

db/themes/pure, docs/Themes.md
Following oh-my-fish/#227, @rafaelrinaldi @edouard-lopez joined forces to make the upstream repository compatible with OMF, including a "theme-pure" alias.
**[pure]** can now join the family of OMF's registered themes. :tada: 
[pure]: rafaelrinaldi/pure
=> registry: add rafaelrinaldi/theme-pure

lib/git/git_ahead.fish
I'm not sure that this is a great change, but perhaps taking out the `awk` script and doing usual Fish checks is a more reasonable approach?
=> git_ahead: Rewrite code, fix ahead being reported as behind

lib/git/git_ahead.fish
My last PR has a bug. :astonished:
Thanks for pointing it out @bpinto @derekstavis
=> bugfix: git_ahead no longer reports 'none' as 'ahead'

lib/git/git_ahead.fish
This fixes the `test` logic, allowing to override the indicators through arguments
=> git_ahead: Fix indicator override

pkg/omf/completions/omf.fish
This is in response to issues #251 and #252.
Changes:
+ Completions for `remove`
+ `cd` and `install` show both plugins and themes
+ `theme` shows only installed themes
It might be a bit slower to initialize, but provides more responsive autosuggestions (according to my short experiments).
=> Improve OMF CLI completions

db/themes/agnoster-mercurial
This theme is deprecated, as mercurial support have been merged into `agnoster`.
=> registry: remove deprecated agnoster-mercurial theme

README.md, pkg/omf/functions/cli/omf.cli.update.fish, pkg/omf/functions/omf.fish
Until now, `omf update` was always "all-in".
This proposal keeps the default behavior, but also let's the user choose to update only the core framework and/or some packages.
- `omf update`: update the framework and all installed packages (default behavior)
- `omf update omf`: update the core framework only
- `omf update agnoster`: only update the agnoster theme
- `omf update balias omf agnoster`: update the core framework, the balias plugin and the agnoster theme. The core framework is always updated first, if included.
=> Allow selective updates

db/pkg/ansible, db/pkg/copy, db/pkg/direnv, db/pkg/extract, db/pkg/gi, db/pkg/hub, db/pkg/iex, db/pkg/keychain, db/pkg/limap, db/pkg/mix, db/pkg/osx_manpath, db/pkg/peco, db/pkg/pyenv, db/pkg/set_color, db/pkg/stamp, db/pkg/tiny, db/pkg/title, db/pkg/vcs, db/pkg/z, db/themes/flash, db/themes/hogan, db/themes/hulk, db/themes/led, db/themes/lolfish, db/themes/russell
A number of plugins in the package database have moved repository locations, or have simply been deleted. This PR updates the URLs of any plugins to their new GitHub locations, and removes entries to plugins that are no longer available.
=> Update plugin URLs and remove broken plugin entries

db/pkg/direnv
This is a brand new plugin following the best conventions and open to expansion.
=> registry: point direnv plugin to organization's version

lib/available.fish, pkg/omf/functions/compat/available.fish
This PR officially marks available as deprecated, moving the
deprecated functionality to omf plugin compat quarantine directory.
=> lib: deprecate `available` function

pkg/omf/functions/core/omf.doctor.fish, pkg/omf/functions/util/omf.check.version.fish
Minimum *fish* version: *2.2.0*
* OMF uses `function -V` (`--inherit-variable`) in omf.repo
Minimum *git* version: *1.9.5*
* OMF uses `git -C` in omf.repo
* OMF uses `git --depth 1` in installer
* OMF intends to use `git --depth 1` for package install
=> `omf doctor` checks for fish & git versions

README.md, pkg/omf/functions/cli/omf.cli.reload.fish, pkg/omf/functions/cli/omf.cli.remove.fish, pkg/omf/functions/cli/omf.cli.update.fish, pkg/omf/functions/core/omf.reload.fish, pkg/omf/functions/omf.fish
This commit adds an improved reload code for Oh My Fish, besides
saving the history now the reloading technique keeps directory
history and stack and clears fish_greeting, for a transparent
transition.
The reloading code is now safe regarding to background jobs. exec
wipes fish job control, so the user-facing code under the (just-
introduced by this commit) `omf reload`, and usages under
`omf remove` and `omf update` are now kept safe by a warning.
Recap of the commit:
- Add improved reload code (omf.reload)
- Add a safe reload code (omf.cli.reload)
- Add `omf reload` command
=> Implement safe shell reloading inside omf plugin

pkg/omf/functions/packages/omf.packages.update.fish, pkg/omf/functions/repo/omf.repo.pull.fish
The purpose of this proposal is to generate a more accurate output on omf update. Namely, packages which have no upstream changes now report that they are already up to date.
Since this is a proposal we haven't really discussed before, this is broken into 3 commits (instead of squashed), so it's easier to track the changes and their aims.
Regarding performance, I must admit that I did not time the new code or the old.
Overall the update process should not improve and not deteriorate in terms of performance. The previous git pull is broken apart to a fetch and a merge. Packages without changes skip the merge (and possibly stashing) in return for an additional check. Packages with changes pay just one more check. If git does any more optimizations in combining the fetch and merge when …
=> omf update: Report up-to-date packages as such

pkg/omf/functions/cli/omf.cli.update.fish
Due to an oversight in my PR #285, OMF core update reports failure whenever the core is already at the latest revision. This is a simple bugfix for immediate resolution.
As further improvement it's possible to differentiate "updated just now" from "was already up to date" message, but it's not urgent by any means.
=> bugfix: Core update reported failure when up-to-date

docs/en-US/FAQ.md, docs/en-US/Packages.md
There were broken links to the translated docs.
I have changed `docs/` to `../`, now it's fine.
=> Fixed links in the english docs.

db/pkg/code
VSCode can now add the `code` command to PATH by itself.
=> Remove vscode plugin

pkg/omf/functions/cli/omf.cli.describe.fish, pkg/omf/functions/cli/omf.cli.help.fish, pkg/omf/functions/packages/omf.packages.describe.fish
Describe all packages got broken when the package structure changed in 49dda5c2f70517ccb063a264c9aa69744a980aa2. I've added back the functionality to describe all packages.
Also a small doc indent fix too.
=> Describe all packages fixed

README.md, docs/en-US/Packages.md, docs/zh-CN/Packages.md, docs/zh-CN/README.md, init.fish, lib/require.fish, pkg/omf/init.fish, pkg/omf/templates/pkg/completions/{{NAME}}.fish, pkg/omf/templates/pkg/functions/{{NAME}}.fish, pkg/omf/templates/pkg/init.fish, pkg/omf/templates/pkg/uninstall.fish, pkg/omf/templates/themes/fish_greeting.fish, pkg/omf/templates/themes/fish_prompt.fish, pkg/omf/templates/themes/fish_right_prompt.fish, pkg/omf/templates/themes/fish_title.fish
Now use pure globbing to generate 100% valid function and
completion paths, effectively splitting the init process in two
steps, one which paths are added, and other when initialization
is done (sourcing init).
This initialization code introduces a new interface for
`init.fish` hook, which deprecates the previously used event
model. The new interface injects three variables into `init.fish`:
path, package and bundle. This variables can be used by the
package to autoload paths, use bundled files, etc.
Also supports key bindings by sourcing
$OMF_CONFIG/key_bindings.fish and also key_bindings.fish in
packages (plugins and themes) root directories. This is done
when fish_user_key_bindings is called.
=> init: rewrite init process

lib/autoload.fish
Refactor autoload: Split the big function into two smaller ones,
doing only option parsing at main function.
The algorithm is also rewritten, now in two steps for both path
inclusion an exclusion functions: 1) use auxiliary lists to store
valid function and completion paths, 2) bulk insert or remove just
once in the variable.
Now also respects path insertion policy, keeping user function
path always in front of other paths, thus allowing precedence of
user functions.
=> autoload: refactor for conformance and performance

init.fish
It was somehow reverted to `1.1.0-dev`
=> init: set correct version number (#323)

pkg/omf/init.fish
Self-explanatory. The search function wasn't in the autoload list.
=> Fix autoload functions

init.fish, pkg/omf/functions/themes/omf.theme.set.fish
This PR fixes the way themes key bindings are treated.
Previous to this PR all installed themes key bindings would be loaded. This PR makes startup code load only current theme key bindings, when existent. 
Also, previously, key bindings wouldn't be reloaded on theme change. This reloads key bindings file when it's found on the theme.
----
@tannhuber, I see your themes use key bindings. Would you like to help us test this PR?
To enable automatic key binding load on themes, move all `bind` calls to `key_bindings.fish` file in theme's repository root directory.
This PR should make `omf t dangerous; omf t budspencer` use `budspencer` key bindings.
=> Fix theme key bindings

db/pkg/ssh-term-helper
Please also remove the oh-my-fish/plugin-ssh repository which contains an older, ambiguously-named version of this plugin which appears to have been bulk-imported, and contains an incorrect LICENSE file.
=> Change ssh-term-helper repository prefix from pkg to plugin to meet new convention

lib/require.fish
This PR fixes a typo in `require` function that made completions not be autoloaded at shell startup.
=> require: fix completions autoload

db/pkg/peco
When I upgraded my omf peco stopped to work I had to change the repo to this one that seems the one the is currently maintainable.
=> Update peco repo

bin/install, templates/config.fish
If we want to evaluate `$OMF_PATH at init time instead of install time, this is how we can do it. A fair reason we might want to do this is it makes putting `config.fish` into a dotfiles repo make more sense. Currently hardcoding the paths makes the config file machine-specific.
=> Evaluate OMF_PATH at init time to fix #136

pkg/omf/functions/cli/omf.cli.help.fish
The huge amount of extra whitespace the help texts used annoyed me, especially on devices with smaller screens or in smaller terminals. Aligned the text to be against the left edge like most applications.
=> Align help text to use less extra space

db/pkg/virtualfish
I am using the [virtualfish](http://virtualfish.readthedocs.io/en/latest/install.html#installing) to manage the python virtual environments and didn't want to put `eval (python -m virtualfish)` into my `config.fish` or `init.fish`. So I created this plugin to manage this functionality easier.
I have noticed some themes had integrated the virtualfish, but I find having it wrapper in a plugin more flexible.
=> Add virtualfish plugin to the registry

docs/en-US/Packages.md, pkg/omf/functions/packages/omf.packages.install.fish, pkg/omf/functions/packages/omf.packages.remove.fish, pkg/omf/functions/packages/omf.packages.run_hook.fish, pkg/omf/functions/packages/omf.packages.update.fish
This pull request adds a new (or rather, revamped) "hooks" system for packages to tap into during the package's lifetime. Similar to Git hooks, OMF hooks are Fish shell scripts located in a `hooks/` directory inside a package. When a particular hook is triggered, the corresponding script is run, if it exists.
The following hooks are implemented:
- `install`; Triggered when the package is first installed via `omf install`. Useful for installing custom dependencies.
- `update`: Triggered when the package is being updated via `omf update`. Useful for updating submodules, etc.
- `uninstall`: Triggered when the package is removed via `omf remove`. Subscribers can use the event to clean up custom resources, etc.
For consistency, the `uninstall` hook is now in the `hooks/` directory, same as the …
=> Add hooks system for packages

pkg/omf/functions/themes/omf.theme.set.fish
This fixes a rare case when fish's builtin function `__fish_reload_key_bindings` is not defined.
=> key bindings: test if reload function is available

.travis.yml, Dockerfile, README.md, bin/install, pkg/omf/functions/cli/omf.cli.destroy.fish, pkg/omf/functions/core/omf.destroy.fish, tools/travis-install-git.sh
Completely refactors the installer. The code is more organized and should be more reliable and consistent.
The new installer supports:
- offline installation (#167, #185)
- interactive questions and acknowledgements
- preserving and ignoring user's config files (#267, #274, #281)
- bootstrap code in `config.fish` is no longer required for Fish 2.3.0+, uses `conf.d` instead
- customizable install paths via command flags
=> Refactor installer to support offline installs and more control over user data

db/pkg/archlinux
This adds again Arch Linux plugin, which was left out of registry in one of our silly plugin structure migrations.
=> registry: add archlinux plugin (fix #395)

bin/install
A suggestion for resolving issue #398, this ensures that the correct error message is displayed if the users environment does not meet the requirements
=> assert fish version before asserting commands

db/pkg/cd
Package cd provides a new cd command to help you change the current working directory fast. It's a proxy directive of the buildin cd command with an alias of going to the upper directory.
I used to enjoy this feature all the time in `zsh` shell. I don't see there is any reason for my dear fish not having it.
=> add pkg cd

db/pkg/gi, db/pkg/tiny
Fix for #404
A couple of db pkg entries were pointing to fishery rather than the core plugins.
=> fix db pkg entries pointing away from core plugins

README.md, bin/install, init.fish, pkg/omf/completions/omf.fish, pkg/omf/functions/cli/omf.cli.channel.fish, pkg/omf/functions/cli/omf.cli.help.fish, pkg/omf/functions/cli/omf.cli.update.fish, pkg/omf/functions/cli/omf.cli.version.fish, pkg/omf/functions/core/omf.channel.get.fish, pkg/omf/functions/core/omf.channel.set.fish, pkg/omf/functions/core/omf.core.update.fish, pkg/omf/functions/core/omf.version.fish, pkg/omf/functions/omf.fish
This PR introduces support for release versioning for the core framework to address issue #10. The update process is divided up into different _update channels_; currently the ~~`release`~~ `stable` and `dev` channels are implemented.
Updating the core framework is now split depending on what the current update channel is. If the user is on the `dev` update channel, updates will behave exactly the same way as previous versions. If the user is on the ~~`release`~~ `stable` channel (the default), updating will instead fetch and checkout the newest tag from GitHub.
The user can view, or change, their current update channel with a new command `omf channel`.
In addition, the installer also selects the latest stable version when cloning and installing the core framework from GitHub.
~~_Note:_ …
=> Implement update channels to introduce release versioning

pkg/omf/functions/core/omf.core.update.fish, pkg/omf/init.fish
Partially fixes #440. Use specific colors instead of using whatever colors are set for Fish's internal use, which could change (and did in 2.4.0).
=> Make OMF command colors independent of Fish version

docs/Themes.md
I noticed the screenshot was going to a non existent screenshot file, so I redirected it to the screenshot provided in the original git repo for the Pure theme.
=> Pure theme screenshot fixed to theme git repo screenshot

db/pkg/pj
This PR adds a new plugin, which is a port of the oh-my-zsh `pj` plugin.
See this repository for details
https://github.com/esphen/plugin-pj
=> Add the Project Jump plugin

pkg/omf/functions/core/omf.doctor.fish
Since there are some common things we need to know when troubleshooting OMF, this adds some relevant diagnostic information so far as output to the `omf doctor` command. We can then recommend users simply paste the output of `omf doctor` as long as it is accessible, or literal `omf.doctor` otherwise.
This does not aid troubleshooting the installation process itself. It might be useful to separate the doctor into its own script that can be downloaded and used separately.
=> Print some useful diagnostic info in `omf doctor`

.gitattributes
Force all Fish scripts in this repo to be checked out using LF line endings.
Prevents problems documented in issues #217, #379, and #444.
=> Ensure Fish scripts always use LF line endings, otherwise multiline commands break

Dockerfile, bin/install, lib/autoload.fish, pkg/omf/functions/bundle/omf.bundle.add.fish, pkg/omf/functions/cli/omf.cli.channel.fish, pkg/omf/functions/cli/omf.cli.install.fish, pkg/omf/functions/cli/omf.cli.new.fish, pkg/omf/functions/cli/omf.cli.remove.fish, pkg/omf/functions/cli/omf.cli.submit.fish, pkg/omf/functions/cli/omf.cli.theme.fish, pkg/omf/functions/core/omf.channel.set.fish, pkg/omf/functions/omf.fish, pkg/omf/functions/packages/omf.packages.cd.fish, pkg/omf/functions/packages/omf.packages.describe.fish, pkg/omf/functions/packages/omf.packages.install.fish, pkg/omf/functions/packages/omf.packages.new.fish, pkg/omf/functions/packages/omf.packages.remove.fish, pkg/omf/functions/packages/omf.packages.submit.fish, pkg/omf/functions/packages/omf.packages.update.fish, pkg/omf/functions/repo/omf.repo.pull.fish, pkg/omf/omf.update.fish, tools/generate-themes-doc.fish, tools/travis-github-pr-integration.sh
Fixes a problem with redirection syntax for Fish >=2.4.0 observed in #454. All redirections are normalized to the correct syntax.
Also bump Fish version in Docker image for better catching of these issues.
=> Normalize redirection syntax

docs/Themes.md, tools/generate-themes-doc.fish
Currently [generate-themes-doc](/oh-my-fish/oh-my-fish/blob/master/tools/generate-themes-doc.fish) fails to fetch the **README.md** file for themes that have the '.git' suffix in their database URL.
A simple `sed` replace solves this issue.
(Replacing #232. The code changed a little bit. Also regenerated Themes.md, which hadn't been updated in a long while)
=> [generate-themes-doc.fish] Ignore '.git' suffix on theme URLs

README.md
Use HTTPS schema instead of cleartext HTTP.
SSL certificate provided by letsencrypt.com, installed on private nginx server for redirection.
Moving to the private server should solve the issue with NameCheap's URL redirection service that didn't behave so well lately (see: #478, #489).
The move to HTTPS is a reasonable and meaningful step towards a safer environment for OMF users (see discussion in #482).
=> Get oh-my-fish installer from a secure connection.

pkg/omf/functions/packages/omf.packages.install.fish
When installing a package from outside a repository, we currently need to detect if it is a theme or package. We were doing this by checking for a `theme-` prefix, but this enforces repo names on package authors and is too restrictive. Instead, detect a theme by checking for the presence of a `fish_prompt.fish` file, which should be much more reliable.
Fixes #191.
=> Detect themes by fish_prompt instead of name

pkg/omf/functions/index/omf.index.query.fish
Full text search outside of name and description seems to make the search _less_ useful. For example, searching for "git" returns every possible package, because they all have "github" in the repo URL. Similarly searching for other fields seems to reduce the usefulness of the results.
This tightens up the search by applying full text search queries to only the package name and description.
=> Limit search to name+description

README.md
Fixed the link of the MIT license shield to LICENSE instead of LICENSE.md. The latter 404'd
=> Fixed License shield link in README.md

docs/en-US/Packages.md
When creating new plugins the word 'pkg' does not exist for 'omf new' command.
The correct one is 'omf new plugin'.
I am creating a omf plugin and saw that issue/typo at the documentation. 
It is a simple contribution.
=> Typo: Update example to use correct command

pkg/omf/functions/packages/omf.packages.new.fish, pkg/omf/templates/pkg/LICENSE, pkg/omf/templates/themes/LICENSE
This changes the [themes] and [pkg] LICENSE files to use a dynamic `year` variable.
The year is calculated using `set -l year (date +%Y)`.
Fixes #593.
[themes]: https://github.com/pxgamer/oh-my-fish/blob/feature/fix-omf-new-year/pkg/omf/templates/themes/LICENSE
[pkg]: https://github.com/pxgamer/oh-my-fish/blob/feature/fix-omf-new-year/pkg/omf/templates/pkg/LICENSE
=> Fix 'omf new' year in LICENSE files

lib/require.fish
Addreses https://github.com/oh-my-fish/oh-my-fish/issues/665
=> Put conf_file loop outside of init_file loop

bin/install, init.fish, pkg/omf/functions/index/omf.index.query.fish, pkg/omf/functions/omf.fish, pkg/omf/functions/themes/omf.theme.set.fish
Since Fish Shell 3.0 [1], `?` as a glob is deprecated. Fixes #644
1. https://github.com/fish-shell/fish-shell/releases/tag/3.0.0
=> Remove occurrences of `?` as a glob

lib/git/git_is_touched.fish
This used to use `git status --porcelain`, which by necessity needs to
check the entire repo for all kinds of changes, just to figure out if
there are any.
Instead, we now use git commands that can exit early.
In large repos, this can be faster by a factor of 15 or so.
Fixes #624.
=> lib/git/git_is_touched: Speed up

init.fish, pkg/omf/functions/themes/omf.theme.set.fish
This enables themes that have conf.d files to have those files loaded. Currently, only plugins have their conf.d file loaded, so themes that depend on their own conf.d can break, if no workarounds are used. The main theme where I encountered this problem is [pure](https://github.com/rafaelrinaldi/pure) which relies on its conf.d to do some setup (see rafaelrinaldi/pure#89).
Fixes #658 
* Load conf.d snippets for the current theme on init (if the current theme has conf.d snippets)
* Load conf.d snippets for new theme on theme change
```
Oh My Fish version:   6
Git version:          git version 2.22.0
```
=> Enable conf.d loading for themes

lib/autoload.fish
The auto loader lacked quotation marks around a variable. This PR fixes that and with this the bug described in #698. I tested it under both fish 2.7 and 3.0, that's also the reason why I'm attaching two environment reports.
Fixes #698 
**Environment report for fish 2.7**
```
Oh My Fish version:   6
Fish version:         fish, version 2.7.1
Git version:          git version 2.11.0
```
**Environment report for fish 3.0**
```
Oh My Fish version:   6
Git version:          git version 2.21.0 Git version:          hub version 2.11.2
```
=> Add missing quotation marks in autoloader

pkg/fish-spec/basic_formatter.fish
One math expression had a simple syntax error.
Fixes #704 
```
Oh My Fish version:   6
Git version:          git version 2.21.0 Git version:          hub version 2.11.2
```
=> Fix bogus math expression in basic_formatter

pkg/omf/functions/bundle/omf.bundle.remove.fish, pkg/omf/functions/packages/omf.packages.remove.fish
Call `command rm` instead of `rm` in `omf destroy` since `rm` may be aliased to something else and fail.
Fixes #717
```
Oh My Fish version:   6
Git version:          git version 2.23.0
```
=> Call the rm binary directly

tools/travis-github-pr-integration.sh
Fixing one more error where we used a caret for IO redirection which is no longer valid
```
Oh My Fish version:   6-48-g6e5cae8
Fish version:         fish, version 3.1.0
Git version:          git version 2.25.0 Git version:          hub version 2.14.1
```
=> fix one more caret error

.travis.yml, AUTHORS, tools/generate-authors.fish
- Update author generation script to retain existing ones.
- Generate updated AUTHORS list.
Note that this includes a little bit of manual deduplication, as we have several contributors who have used different names for the same email address (or different email addresses for the same name?). Future updates to this list will need to manually dedupe as well.
=> Update AUTHORS list

docs/Themes.md
Discovered while setting up the kawasaki theme, that there was a small typo in `Themes.md`. 
Found correction in the [kawasaki repo](https://github.com/hastinbe/theme-kawasaki/blob/e5c3a7c33485fe3fe28c66fd3dd924ac6c8eac98/fish_prompt.fish#L40).
=> Fix small typo

pkg/omf/functions/index/omf.index.path.fish
`XDG_*` or `HOME` variables might contains extra slash at the end of path (I don't know if this is against specification). This double slash might disturb comparison and make them false positive. The consequence is as described in the issue.
The error can happen at the first time OMF installed thus might block potential new user.
Fixes #774 
```
Oh My Fish version:   7
Git version:          git version 2.25.4
```
=> Fix double slash in index path

pkg/omf/functions/packages/omf.packages.install.fish, pkg/omf/functions/packages/omf.packages.update.fish, pkg/omf/functions/repo/omf.repo.clone.fish, pkg/omf/functions/repo/omf.repo.pull.fish
See #678.
Find branch information in the repository first and then clone (or pull). If package doesn't have a branch attribute, `master` is used as the default branch.
Maybe more test is needed for it (especially for function `omf.repo.pull`). I only test them on several packages and themes and it works well, but I don't know wethear this project has some unit tests to go through.
=> Add branch information for install and update package

.github/workflows/build.yml
This is somehow useless as secrets are not passed to action runners when the workflow is triggered from a forked repository (for obvious reasons)
=> workflow: Send no notification on Slack

pkg/omf/functions/packages/omf.packages.install.fish, pkg/omf/functions/repo/omf.repo.clone.fish
This allows `omf.repo.clone` to clone from a repository's default branch if no branch is specified. This fixes package installation from a URL, which previously would not work because no branch was specified.
Fixes # (issue)
```
Oh My Fish version:   7-31-gf4e61aa
Fish version:         fish, version 3.1.2
Git version:          git version 2.25.1
```
=> Do not set default branch during package installation

pkg/omf/functions/packages/omf.packages.install.fish
This makes the installer more flexible in detecting if a package is a theme when it is not specified from the package repository by looking in the top level directory and the `functions` directory for the `fish_prompt.fish` file.
```
Oh My Fish version:   7-31-g251a792
Fish version:         fish, version 3.1.2
Git version:          git version 2.25.1
```
=> Improve detection of theme packages during installation

docs/cli/omf.adoc, docs/cli/theme.adoc, pkg/omf/completions/omf.fish, pkg/omf/spec/basic_spec.fish
As _omf theme <name>_ won't install a theme per se, changing "install" to "activate" seems clearer. So _omf theme_ will list installed and available themes, activate an installed one, but won't install one.
Fixes # (issue)
```
Oh My Fish version:   7
Fish version:         fish, version 3.1.0
Git version:          git version 2.26.0
```
=> I tiny change to make omf theme doc clearer

pkg/omf/functions/core/omf.doctor.fish, pkg/omf/functions/repo/omf.repo.remote_uri.fish, pkg/omf/functions/repo/omf.repo.uri_components.fish
For each installed package (plugin or theme), the doctor compares the remote URI (default remote configured for fetch on branch 'master') with the URI that's specified in the local package database.
If the _host_, _path_ or _repository name_ differs, a warning is issued. Protocols, logins and ports doesn't matter in this comparison.
As an example, `http://oranja@github.com/path/repo` in the database should have no problem with `git@github.com:path/repo.git` as the remote URI.
Warnings are also issued for installed packages that have no corresponding database entry. The exceptions to this rule are the built-in `omf` and `fish-spec` packages.
=> doctor: check if Git remotes match db URLs

.github/workflows/build.yml
`ubuntu-16.04` has been removed from [virtual-environments](/actions/virtual-environments) while `macos-11` has been added.
=> workflow: Update virtual environments

README.md
Relying on some external domain seems like a bad idea after so many recurring issues. We're certainly better off with a slightly longer URL.
Fix #867
=> README: Use GitHub for the install script

pkg/omf/functions/bundle/omf.bundle.install.fish
After a package dependency was installed from the bundle file, the dependency package was not available for use by the plugin to be installed,. Thus, causing issues with plugins which relied on dependency packages during installation. Added require to packages installed from bundle file as dependencies. 
Fixes Related Issue: https://github.com/oh-my-fish/plugin-weather/issues/38
```
Oh My Fish version:   7-35-g3c0c810
Fish version:         fish, version 3.3.1
Git version:          git version 2.32.0
```
- [*] My code follows the [style guidelines](https://github.com/oh-my-fish/oh-my-fish/blob/master/CONTRIBUTING.md#code-style) of this project
- [*] I …
=> Require bundle package after install

docs/en-US/Packages.md, pkg/omf/functions/packages/omf.packages.remove.fish
This changes the `remove` script to check if an `uninstall.fish` script exists before running it. It also fires `{$pkg}_uninstall` and `uninstall_$pkg` events whether or not the file exists. This improves support for nonstandard uninstall hooks.
```
Oh My Fish version:   7-31-ga579039
Fish version:         fish, version 3.1.2
Git version:          git version 2.25.1
```
=> Improve nonstandard uninstall events for backwards compatability

README.md, pkg/omf/functions/packages/omf.packages.install.fish, pkg/omf/functions/repo/omf.repo.clone.fish
Allows installation from GitHub repositories with `user/repo` syntax. Shorthand for URL syntax, more or less, with GitHub as the forge.
Fixes #818 
```
Oh My Fish version:   7-35-g332ca07
Fish version:         fish, version 3.1.2
Git version:          git version 2.25.1
```
=> Installation with user/repo syntax

pkg/omf/functions/packages/omf.packages.name.fish, pkg/omf/spec/omf_packages_spec.fish
With this change, `omf.packages.name` escapes a dot that was matching any character and extracting partial names from names or URLs.
Fixes #901
=> omf.packages.name: Fix regex by escaping a dot

pkg/omf/functions/repo/omf.repo.pull.fish
Somewhat related to #905 and #685, but by use-case is not a package in packages-main repo, but a [GitLab repo](https://gitlab.com/txlab/fish-functions), for which install currently works fine, but `omf update` results in this:
(on `omf channel dev`)
```
Oh My Fish is up to date.
You are now using Oh My Fish version 7-44-gd428b72.
Updating https://github.com/oh-my-fish/packages-main master... Done!
fatal: couldn't find remote ref refs/heads/master
Could not update fish-functions.
bobthefish is already up-to-date.
default is already up-to-date.
```
While debugging I found `set branch "master"` in `pkg/omf/functions/repo/omf.repo.pull.fish` and changed it to use current branch as fallback/default an old convention
I tried thinking of all the edge-cases you're covering, but not sure if I …
=> Support installing repo from URL with non-master branch

README.md
Seems like this is likely to happen again in the future -- people will remember to update the SHA256 file but not the`README.md`. Couldn't find a way to embed a file into markdown, maybe add this as another checkbox in the PR template? Or remove the hash from the README.md entirely?
=> Fix #924: Checksum isn't up to date in readme

.github/workflows/build.yml, tools/ci-install-fish.sh
Well, it happens that CI is currently completely broken. Linux and macOS versions have been retired from GH actions. This updates CI to run on Fish 3.0 and 4.0, as well as on least recent supported and most recent supported Linux and macOS operating systems.
=> chore: update CI to latest OS and Fish versions

lib/require.fish
The $path variable when evaluating `conf.d` scripts was being set to the last package `init.fish` path. This fixes it so it points to the root of the package.
```
Oh My Fish version:   7-62-gbae61e4
Fish version:         fish, version 4.0.2
Git version:          git version 2.39.5 (Apple Git-154)
```
=> fix conf.d $path variable
