- init.fish
- lib/autoload.fish
- pkg/omf/omf.fish
We have lots of bad code around the repository. It's time to start moving away from this codebase.
> Beginning of many PRs to clean up the code

- db/pkg/python
Referencing oh-my-fish/plugin-python#1
> Add python plugin

- pkg/omf/cli/omf.install.fish
- pkg/omf/cli/omf.persist.fish
- Add support for persisting theme information.
- Use documented private function naming scheme.
> Extract _write_bundle to omf.persist

- db/themes/cmorrell
Just fixed the repository path
> Updated cmorrell theme url

- pkg/omf/cli/omf.bundle.add.fish
- pkg/omf/cli/omf.bundle.install.fish
- pkg/omf/cli/omf.bundle.remove.fish
This comes to fix #42 and also makes code more homogeneous by reusing code patterns.
> bundle: make contents unique when adding and installing bundle

- db/pkg/vundle
Dependent on https://github.com/oh-my-fish/plugin-vundle/pull/1
> Add vundle pkg back into db.

- pkg/omf/cli/omf.bundle.install.fish
Well I just found this fix for the issue #45
> Using raw `name_or_url` instead of `name`.

- db/pkg/fzf
A command-line fuzzy finder written in Go
> add reference to package 'fzf'

- .travis.yml
Command: `travis encrypt "..." --add notifications.slack`
> Travis integration for slack

- README.md
We are using slackin (https://github.com/rauchg/slackin) to automatically accept people's invitation.
> Replace gitter with slack

- db/themes/nelsonjchen
This is a theme that's based off of the re5et theme from oh-my-zsh with some modifications for my preferences.
> Add nelsonjchen theme to db

- bin/install
- pkg/omf/cli/omf.install.fish
- pkg/omf/cli/omf.repo.pull.fish
- pkg/omf/omf.fish
Hey there,
Just moved some commit from #52 to a new PR.
> Remove some pushd popd, using git --git-dir --work-tree

- db/themes/pastfish
- docs/Themes.md
add my theme: https://github.com/chgu82837/PastFish
> add pastfish theme

- init.fish
- lib/autoload.fish
- lib/available.fish
- lib/require.fish
- pkg/omf/init.fish
- pkg/omf/omf.fish
- Initial work for supporting plugin dependencies.
- Source `init.fish` over `$package_name.fish`.
> Faster loading

- README.md
- docs/zh-CN/README.md
I forgot to update the install instructions on both README on #77. Here come the fixes.
> Update installation script instructions

- bin/install
This was left as a remnant of #93. Fixed now.
> Remove reload notice from installer script

- docs/zh-CN/README.md
Update README to reflect the header changes in english README file.
> Update zh-CN readme header

- bin/install
- pkg/omf/cli/omf.destroy.fish
:100: 
This avoids clean installs to start with theme issues.
> install: Remove existing fish_prompt by backuping

- db/pkg/git-flow
- db/pkg/vi-mode
plugin was compatible with new architecture without modification. updated pkg db
> Convert plugin to new OMF architecture

- pkg/omf/completions/omf.fish
I noticed the doctor command had been added put didn't see it in the completions.  Also remove the no longer valid query and version.
> update some cli completions: remove query and version. add doctor

- db/pkg/thefuck
We're good to go using our very own thefuck plugin. OMF FTW! Please review, and comment, these are much welcome.
> refact(pkg/thefuck): use a better, oh-my-fishy thefuck plugin

- db/pkg/jump
> Add jump plugin repo

- pkg/omf/cli/omf.repo.pull.fish
From the *little annoyances* series.
> omf.repo.pull: Simplify stashed flag using set -q

- db/themes/sushi
- docs/Themes.md
This PR adds a new theme named [Sushi](https://github.com/umayr/theme-sushi/).
* Minimal Prompt.
* Git Support.
* Displays `^` when there are stashed changes.
* Displays `*` when there are any changes to files already being tracked in the repo.
* Displays current branch name.
* Branch name color changes when there are staged changes.
* Displays number of commits current branch is ahead/behind from origin.
* By default it shows only the name of the current directory but it provides a flag `theme_complete_path` to display abbreviated current working directory instead.
* Displays Time.
> Add a new theme: Sushi.

- db/pkg/fonts
Add this simple font manager to registry
> registry: add fonts package

- db/pkg/battery
Update reference to our own compatible fork of this package.
> registry: Update battery plugin reference

- docs/zh-CN/README.md
- Add Update Instructions
- Add preview available Themes
> Update zh-CN README

- db/pkg/wd
wd (warp directory) lets you jump quickly to custom directories.
Made a new pull request because I messed up the last one.
> submit wd plugin.

- db/themes/batman
> registry: Update batman theme reference

- db/pkg/php-version
> registry: add php-version plugin

- db/pkg/shark
Add a Shark plugin ported to OMF.
> Add shark plugin

- db/pkg/iex
- db/pkg/mix
Add `iex` & `mix` plugins for elixir develop environment.
> registry: Add iex&mix plugins

- db/pkg/powerline
> add powerline

- db/pkg/balias
> registry: add oh-my-fish/plugin-balias

- .gitignore
- .travis.yml
- pkg/fish-spec/functions/assert.error_message.fish
- pkg/fish-spec/functions/assert.expand_operator.fish
- pkg/fish-spec/functions/assert.fish
- pkg/fish-spec/functions/fish-spec.fish
- pkg/fish-spec/spec/assert_error_message_spec.fish
- pkg/fish-spec/spec/results_spec.fish
- pkg/omf/spec/basic_spec.fish
Adding a very simple test framework.
Initially I have added some very basic tests for the omf framework.
> Test suite

- templates/config.fish
Replacing #209. Sorry for the mess.
> Fix issue #197: quote OMF_PATH

- db/themes/shellder
- docs/Themes.md
[Shellder](https://github.com/simnalamburt/shellder)
---------
> Things are beautiful if you love them. *[Jean Anouilh]*
Shellder is a fork of agnoster, with smarter functionalities
1. No solarized colorscheme
2. Distinguishs untracked, unstaged and staged change.
3. [etc](https://github.com/simnalamburt/shellder/commits/master)
Please add this to the default db!
[Jean Anouilh]:   https://en.wikipedia.org/wiki/Jean_Anouilh
> New theme: shellder

- db/pkg/fasd
1. ~~https://github.com/simnalamburt/pkg-cgitc~~
2. https://github.com/simnalamburt/pkg-fasd
3. ~~https://github.com/simnalamburt/pkg-sensible~~
--------
Existing fasd plugin doesn't even work properly.
- No fasd_cd
- No default aliases (f, a, s, d, z, zz, ...)
So I forked it and totally rewrote it. Please consider it as different plugin.
> Update package: fasd

- README.md
- docs/zh-CN/README.md
Oh My Fish has been stable for many months, we no longer need the update
instructions on the main README.
> Remove update instructions

- docs/Themes.md
I missed an update to [pure]'s Readme.md in the last PR (#231). :flushed:
Should fix the failing build.
[pure]: /rafaelrinaldi/pure
> Update theme docs (Themes.md)

- db/themes/lolfish
- docs/Themes.md
Add this nice colorful theme from @er0
> registry: Add lolfish theme

- db/themes/chain
- docs/Themes.md
I made a new theme! Add it to the database?
Hopefully the theme isn't too similar to other themes -- I tried to distinguish it a bit. Check it out here: https://github.com/oh-my-fish/theme-chain.
> Add chain theme to db

- db/themes/es
https://github.com/eugenesvk/omf-theme-es
Per https://github.com/oh-my-fish/oh-my-fish/pull/244 didn't change `Readme.md`.
> Added a new theme `es` with properly formatted remote name 

- db/pkg/code
Command line for Visual Studio Code
> Add Visual Studio Code plugin

- docs/Themes.md
Updates Themes.md adding @eugenesvk theme from #246
> docs: update Themes.md

- db/pkg/phpbrew
https://github.com/oh-my-fish/plugin-phpbrew
> Add phpbrew plugin to database

- db/pkg/termux
Adds a [weird, obscure plugin](https://github.com/coderstephen/plugin-termux) to the database.
> Add termux plugin to database

- db/pkg/argu
Adds the argu plugin to the database.
> Add argu plugin to database

- db/pkg/expand
Adds the shiny new and awesome word expansion plugin to the public database.
> Add expand plugin to database

- db/pkg/ssh-config.d
Add [ssh-config.d](https://github.com/rominf/oh-my-fish_plugin-ssh-config.d) plugin to database
> Add ssh-config.d plugin into database

- db/pkg/hash
Forgot to add the hash plugin to the database when I wrote it. :wink:
> Add hash plugin to database

- db/themes/cyan
https://github.com/szwathub/omf-theme-cyan
can get more information about time since last commit and so on.
> Added a new theme named cyan

- README.md
It seems to me that a major confusion point when submitting a package is the _url_ portion. So I decided to clarify that part of the README a bit. I also fixed a very small error. :smile:
> Small Readme Fixes

- db/themes/mokou
https://github.com/tentakel/mokou
> add mokou to the theme registry

- db/pkg/wttr
Add a wttr plugin to omf that interfaces with wttr.in service and shows weather information
> Add wttr plugin to omf

- pkg/omf/functions/cli/omf.cli.help.fish
- pkg/omf/functions/cli/omf.cli.list.fish
- pkg/omf/functions/packages/omf.packages.list.fish
> list: refactor code, fix fish 2.3.0 globs

- bin/install
Per fish-shell/fish-shell@95635a5
> Inspect $FISH_VERSION variable instead of $version

- pkg/omf/templates/pkg/README.md
- pkg/omf/templates/themes/README.md
> Make templates consistent

- db/pkg/exenv
Simple package to make exenv play nice with fish-shell.
> Adds the exenv package

- docs/en-US/Packages.md
makes package docs better by refreshing hooks documentation
and also contributing process.
> docs/packages: better documentation

- db/pkg/docker-machine
https://github.com/oh-my-fish/plugin-docker-machine
> Add docker-machine plugin

- db/pkg/sudope
With Fish 2.3 and key binding support from OMF, this plugin can do its business elegantly.
> Add "sudope" to the registry

- init.fish
Fixes fish-shell/fish-shell#3186
> Fix double key bindings load

- lib/git/git_branch_name.fish
> lib/git: fix branch name in detached head

- CONTRIBUTING.md
gives some fresh air to contributing, reflecting more our current style and redaction.
> CONTRIBUTING: give some fresh air

- README.md
> Add keybindings file to dotfiles list in readme

- db/themes/fishbone
Hi, 
I've created a theme called Fishbone.  As suggested in Oh my fish [documentation](https://github.com/oh-my-fish/oh-my-fish#omf-submit-pkgname-url), I am sending you a Pull Request to update themes registry.
I've tested theme using: 
* omf submit
* omf doctor
* omf install
Here is a link to [Fishbone theme](https://github.com/pantuza/fishbone)
Congrats for Oh my fish project!  It really rocks : )
> Fishbone theme for fish shell managed by Oh my fish

- db/pkg/termux
- db/pkg/tmux-zen
My username has changed :wink:
> Update moved plugin urls

- db/themes/eden
An evolution of theme "edan" 😄 
https://github.com/amio/fish-theme-eden
> Add "eden" to theme registry.

- pkg/omf/functions/packages/omf.packages.update.fish
> Fix the blank lines in `omf update` output.

- pkg/omf/templates/pkg/LICENSE
- pkg/omf/templates/pkg/README.md
- pkg/omf/templates/themes/LICENSE
- pkg/omf/templates/themes/README.md
I propose some minor amendments to both templates. Please review and comment.
> Amend templates

- db/pkg/aws
> Add AWS plugin

- db/pkg/license
https://github.com/oh-my-fish/plugin-license
> Add plugin license

- db/pkg/dpaste
> Add dpaste

- bin/install
> Do not replace existing theme when installing

- db/themes/kawasaki
[Kawasaki theme](https://github.com/hastinbe/theme-kawasaki)
I wish to maintain my own repo at this time. Thank you
> Add theme kawasaki

- db/themes/slavic-cat
- docs/Themes.md
* Minimal look
* Display branch for Git projects
* Git project dirty status indicator *meow* **(R,C,A,U,M,?)** *meow*
* Fish shell vi mode indicator
* Next line prompt
> Add slavic-cat theme

- db/pkg/emacs
> Fix emacs plugin URL

- db/pkg/dpaste
Remove a bad space from the package URL.
> Fix dpaste bad URL

- db/themes/gentoo
Hi, 
recently I switched to fish on my Gentoo, but I missed my old prompt, so I forked godfather theme and created a new one.
> Add Gentoo theme

- db/pkg/fish_logo
I packaged up the fish_logo function for omf
> Added fish_logo package to registry

- db/themes/emoji-powerline
I created a new theme based on Agnoster that makes more use of the powerline characters in the path prompt and also utilizes emoji characters (which are widely available beyond macOS now thanks to Google's Noto font). Thought I'd submit it in case anyone else is interested in using it.
> Added emoji-powerline theme

- README.md
> Docs on how to set variables in `init.fish` (#328)

- pkg/omf/functions/themes/omf.theme.set.fish
> Update functions directory in function path when setting theme

- init.fish
- pkg/omf/functions/cli/omf.cli.themes.list.fish
- pkg/omf/functions/themes/omf.theme.set.fish
> Handle missing theme setting more gracefully

- docs/pt-BR/FAQ.md
- docs/pt-BR/Packages.md
- docs/pt-BR/README.md
Just changed the files 'FAQ.md', 'Packages.md' and 'README.md' to follow the pattern of the 'Also in' message, at Brazilian translation.
> following the 'Also in' pattern (PT-BR)

- README.md
a small change in the readme file.
> omf search update in readme. --pkg to -p 

- LICENSE
Update license year to 2017 from 2016
> bump LICENSE year

- LICENSE
> Change License Year

- docs/Themes.md
Well, It worked with pastfish, I didn’t bother to check the entire readme.md for more of these.
> Little typos.

- docs/Themes.md
Hi,
I'm a [core maintainer of `pure` prompt](https://github.com/rafaelrinaldi/pure/graphs/contributors).
I simply updated `pure` description with our current readme content.
> update `pure` description to reflect `2.x`

- README.md
- docs/es-ES/FAQ.md
- docs/es-ES/Packages.md
- docs/es-ES/README.md
- docs/pt-BR/README.md
- docs/ru-RU/README.md
- docs/uk-UA/README.md
- docs/zh-CN/README.md
Added the spanish translations for README, FAQ and Packages files
- [x ] My code follows the [style guidelines](https://github.com/oh-my-fish/oh-my-fish/blob/master/CONTRIBUTING.md#code-style) of this project
- [x ] I have performed a self-review of my own code
- [x ] I have commented my code, particularly in hard-to-understand areas
- [x ] I have made corresponding changes to the documentation
- [x ] New and existing tests pass locally with my changes
> Spanish translation for Documentation

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/PULL_REQUEST_TEMPLATE.md
- CHANGELOG.md
- README.md
Prepare files for the next release, v7.
> CHANGELOG: Add updates for version 7

- README.md
- docs/en-US/FAQ.md
- docs/en-US/Packages.md
- docs/es-ES/FAQ.md
- docs/es-ES/Packages.md
- docs/es-ES/README.md
- docs/nl-NL/FAQ.md
- docs/nl-NL/Packages.md
- docs/nl-NL/README.md
- docs/pt-BR/FAQ.md
- docs/pt-BR/Packages.md
- docs/pt-BR/README.md
- docs/ru-RU/FAQ.md
- docs/ru-RU/Packages.md
- docs/ru-RU/README.md
- docs/uk-UA/FAQ.md
- docs/uk-UA/Packages.md
- docs/uk-UA/README.md
- docs/zh-CN/FAQ.md
- docs/zh-CN/Packages.md
- docs/zh-CN/README.md
Add missing links, reorder alphabetically, and fix spacing issues.
> Standardize documentation header links

- pkg/omf/functions/packages/omf.packages.list.fish
- pkg/omf/functions/themes/omf.theme.set.fish
Fix issue #554 
- Enabled pkg/themes in OMG_CONFIG/themes/* to be listed
- Enabled omg.theme.set to check for the theme in OMG_CONFIG/themes/*
> Fix bug when creating new theme

- docs/zh-CN/README.md
I just fixed the Chinese README translation. The Chinese translation seems to be created by machine and have too many grammar problem. I fixed them.
> Fix translation

- docs/Themes.md
- tools/generate-themes-doc.fish
I didn't have much time to invest in `tools/generate-themes.doc.fish`, unfortuntely. It's far from perfect, but fairly usable. Please, refer to instructions in the header.
Fix #795, #800, #771
> Make `generate-themes-doc` usable and update Themes.md

- docs/Themes.md
- tools/generate-themes-doc.fish
> Themes.md: Show a table of themes instead of a long list

- docs/Themes.md
- tools/generate-themes-doc.fish
- Add barracuda and solarfish
- Update bobthefish readme contents
> Regenerate Themes.md

- docs/Themes.md
Ref.: joelwanner/theme-boxfish#1
> Update the screenshot of boxfish

- .github/workflows/build.yml
REF: https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#example-ignoring-paths
> ci(build): ignore if only **.md is editted

- README.md
Remove broken Slack badge from README
Fixes # (issue)
```
Oh My Fish version:   7
Fish version:         fish, version 3.1.0
Git version:          git version 2.26.0
```
> Remove broken Slack badge from README

- pkg/omf/functions/cli/omf.cli.install.fish
Set theme when installed from URL (or user/repo)
> omf.cli.install: Set theme when installing from URL
